Update local-deployment.md with PP config
0xPolygon/polygon-docs-old pull request #2486
Opened 2024-11-12 16:27 UTC by vcastellm

Update doc and especify how to PP chain

2024-11-13 11:50 UTC, mitchpolygon requested changes
@vcastellm Overall it looks good, can you make the following changes please:

1. The system requirements and instructions are different between the PP and FEP local deployment right?
2. Therefore, within the navigation we will need both the FEP and PP local deployment guides
3. Instead of updating the existing file, can you create a new file titled "Pessimistic proofs (PP) guide"
4. Update the existing file to be titled "Full execution proofs (FEP) guide"
5. Nest both of these guides under the "Local deployment guide" navigation section

2024-11-13 17:52 UTC, vcastellm commented
> @vcastellm Overall it looks good, can you make the following changes please:
> 
> 1. The system requirements and instructions are different between the PP and FEP local deployment right?

No, system requirements are the same for both, same for Kurtosis.

> 2. Therefore, within the navigation we will need both the FEP and PP local deployment guides
> 3. Instead of updating the existing file, can you create a new file titled "Pessimistic proofs (PP) guide"
> 4. Update the existing file to be titled "Full execution proofs (FEP) guide"
> 5. Nest both of these guides under the "Local deployment guide" navigation section

Given that the differences are minimal, IMO splitting them in different sections would create a lot of duplication.

Generally, our goal in CDK and in DevTools is to provide users with something that's super easy to use, ideally it should be a one-liner to run the stack, therefore the changes in the document are minimal.

That would create a 98% duplicated documents, I think it doesn't makes sense to artificially create 2 different documents.

I wanted to be more explicit on the configuration doc but we can come up with 2 one-liners for each path:

### PP

`kurtosis run --enclave cdk --args-file "https://raw.githubusercontent.com/0xPolygon/kurtosis-cdk/refs/heads/main/.github/tests/fork12-pessimistic.yml" github.com/0xPolygon/kurtosis-cdk`

### FEP

`kurtosis run --enclave cdk github.com/0xPolygon/kurtosis-cdk`

2024-11-14 09:41 UTC, vcastellm commented
@mitchpolygon I added the oneliners to a new section in the doc called: "Quick setup" that should be the super easy setup process for lazy people, the rest of the document is more detailed setup for curious people.

2024-11-14 16:11 UTC, praetoriansentry commented on docs/cdk/getting-started/local-deployment.md
> +kurtosis run --enclave cdk --args-file "https://raw.githubusercontent.com/0xPolygon/kurtosis-cdk/refs/heads/main/.github/tests/fork12-pessimistic.yml" github.com/0xPolygon/kurtosis-cdk
You might want to set a verision tag or commit hash to future proof against refactors. this would be need both for the args file and for the selector

2024-11-14 16:12 UTC, praetoriansentry commented on docs/cdk/getting-started/local-deployment.md
> +Save this config to `paraml.yml` file, and then run:
`paraml.yml` doesn't match the `params.yml` referenced below

2024-11-14 16:13 UTC, vcastellm commented on docs/cdk/getting-started/local-deployment.md
> +Save this config to `paraml.yml` file, and then run:
typo

2024-11-14 16:16 UTC, vcastellm commented on docs/cdk/getting-started/local-deployment.md
> +kurtosis run --enclave cdk --args-file "https://raw.githubusercontent.com/0xPolygon/kurtosis-cdk/refs/heads/main/.github/tests/fork12-pessimistic.yml" github.com/0xPolygon/kurtosis-cdk
This is even temporary until the release, because it's going to be moved most prob.?

2024-11-15 09:45 UTC, leovct reviewed
lgtm

2024-11-15 09:45 UTC, leovct commented on docs/cdk/getting-started/local-deployment.md
> +kurtosis run --enclave cdk github.com/0xPolygon/kurtosis-cdk
```suggestion
kurtosis run --enclave cdk github.com/0xPolygon/kurtosis-cdk github.com/0xPolygon/kurtosis-cdk
```

2024-11-15 13:46 UTC, mitchpolygon approved these changes

2024-11-15 14:06 UTC, mitchpolygon commented on docs/cdk/getting-started/local-deployment.md
> +### Configure a Pesimistic Proof chain
@vcastellm Could you change it to "Configure a CDK Sovereign chain " please.

2024-11-20 14:25 UTC, merged