CDK: migration steps for 7-8 for partners
0xPolygon/polygon-docs-old pull request #326
Opened 2024-03-26 08:50 UTC by kmurphypolygon

https://polygon.atlassian.net/browse/DOCS-110

2024-03-26 16:20 UTC, Sharonbc01 commented
Hi @kmurphypolygon please do not publish yet. I have asked product @gsilva5 to provide some verbiage for the first section on how CDK owners / IP partners contact Polygon to schedule required upgrade transactions.

2024-03-27 17:03 UTC, Sharonbc01 commented on docs/cdk/how-to/migrate/7-8.md
> +## Process to upgrade from fork 7 to 8
```suggestion
## Process to upgrade from fork 7 to 8 for isolated CDK chains
```

2024-03-27 17:09 UTC, Sharonbc01 commented
@kmurphypolygon  I added a note to indicate this upgrade path is for isolated CDK chains only.

Please can you remove steps 1 to 8. Gabe advised we will create better verbiage for IP Partner from Fork ID 10 onwards when we really need to have this process in place. 

Thus starting the body of the article from Verify all batches works for isolated CDK chains. Thanks

2024-03-27 18:11 UTC, kmurphypolygon commented on docs/cdk/how-to/migrate/7-8.md
> +8. CDK operators update the software and restart all components. Follow the [update software](#update-software) instructions below.
```suggestion
```

2024-03-27 18:12 UTC, kmurphypolygon commented on docs/cdk/how-to/migrate/7-8.md
> +
```suggestion
```

2024-03-27 18:21 UTC, Sharonbc01 commented on docs/cdk/how-to/migrate/7-8.md
> +This document shows Polygon partners how to migrate a CDK stack from fork 7 to fork 8.
```suggestion
This document shows Polygon partners how to migrate an isolated  CDK stack from fork 7 to fork 8.
```

2024-03-27 18:26 UTC, Sharonbc01 requested changes
@kmurphypolygon  as we had to move to Fork ID 9 over the weekend due to zkEVM outage this should probably be reflected. best to replace 8 with 9 through out

2024-03-27 18:26 UTC, Sharonbc01 commented on docs/cdk/how-to/migrate/7-8.md
> +    This process is done collaboratively with Polygon the CDK team.
please delete this sentence

2024-03-27 18:26 UTC, Sharonbc01 commented on docs/cdk/how-to/migrate/7-8.md
> +5. Ask Polygon to send the L1 tx, and wait until confirmation.
Remove this sentence

2024-03-28 09:38 UTC, kmurphypolygon commented on docs/cdk/how-to/migrate/7-8.md
> +    This process is done collaboratively with Polygon the CDK team.
```suggestion
```

2024-03-28 09:38 UTC, kmurphypolygon commented on docs/cdk/how-to/migrate/7-8.md
> +5. Ask Polygon to send the L1 tx, and wait until confirmation.
```suggestion
```

2024-03-28 09:39 UTC, kmurphypolygon commented on docs/cdk/how-to/migrate/7-8.md
> +## Process to upgrade from fork 7 to 8 for isolated CDK chains
```suggestion
## Process to upgrade forks for isolated CDK chains
```

2024-03-28 09:39 UTC, kmurphypolygon commented on docs/cdk/how-to/migrate/7-8.md
> +
```suggestion
```

2024-03-28 09:39 UTC, kmurphypolygon commented on docs/cdk/how-to/migrate/7-8.md
> +This document shows Polygon partners how to migrate an isolated  CDK stack from fork 7 to fork 8.
```suggestion
This document shows Polygon partners how to migrate an isolated CDK stack.
```

2024-03-28 09:40 UTC, kmurphypolygon commented on docs/cdk/how-to/migrate/7-8.md
> +Follow the steps to verify all batches for upgrading from fork 7 to 8.
```suggestion
Follow the steps to verify all batches for upgrading.
```

2024-03-28 09:40 UTC, kmurphypolygon commented on docs/cdk/how-to/migrate/7-8.md
> +2. Wait until synchornizer receives a fork id 8 event (check table `state.fork_id`).
```suggestion
2. Wait until synchornizer receives a fork id event (check table `state.fork_id`).
```

2024-03-28 09:41 UTC, kmurphypolygon commented on mkdocs.yml
> +          - Fork 7 to 8: cdk/how-to/migrate/7-8.md
```suggestion
          - Fork migration: cdk/how-to/migrate/fork.md
```

2024-03-28 09:41 UTC, kmurphypolygon commented on docs/cdk/how-to/migrate/7-8.md
> +
```suggestion
```

2024-03-28 09:43 UTC, kmurphypolygon commented
OK @Sharonbc01 DONE. I removed all fork numbers to make it generic. https://github.com/0xPolygon/polygon-docs/pull/326

2024-04-04 13:05 UTC, hsutaiyu approved these changes
Approved without modifications.

2024-04-04 13:11 UTC, hsutaiyu approved these changes

2024-04-04 14:55 UTC, Sharonbc01 approved these changes

2024-04-04 14:56 UTC, merged