commit first chunk
0xPolygon/polygon-docs-old pull request #440
Opened 2024-05-02 14:49 UTC by kmurphypolygon

2024-05-07 08:06 UTC, vcastellm requested changes
Let's put this on hold as there are some modifications needed to make this more friendly

2024-05-07 08:31 UTC, kmurphypolygon commented
No worries, moving into draft state.

2024-06-10 13:07 UTC, vcastellm commented on docs/cdk/erigon/chain-config.md
> +    You can use any of the example yaml files at the root of the repo as a base and edit as required, but ensure the `chain` field is in the format `dynamic-{network` and matches the names of the con
```suggestion
    You can use any of the example yaml files at the root of the repo as a base and edit as required, but ensure the `chain` field is in the format `dynamic-mynetwork` and matches the names of the config files above.
```

2024-06-10 13:14 UTC, vcastellm approved these changes
LGTM!

2024-07-15 13:12 UTC, revitteth commented on docs/cdk/erigon/chain-config.md
> +5. To use the new config when starting erigon, use the `--cfg` flag with the path to the config file e.g. `--cfg="/dynamic-mynetwork/dynamic-mynetwork.yaml"`.
This should be --config flag :)

2024-07-16 06:56 UTC, kmurphypolygon commented on docs/cdk/erigon/chain-config.md
> +5. To use the new config when starting erigon, use the `--cfg` flag with the path to the config file e.g. `--cfg="/dynamic-mynetwork/dynamic-mynetwork.yaml"`.
Thank you. Updated.

2024-08-13 13:16 UTC, merged