zkEVM: architecture smart contracts bridging/exit roots
0xPolygon/polygon-docs-old pull request #500
Opened 2024-05-30 10:32 UTC by kmurphypolygon

2024-06-04 17:30 UTC, EmpieichO requested changes

2024-06-04 17:30 UTC, EmpieichO commented on docs/zkEVM/architecture/high-level/overview.md
>      - Pool database: The pool database records transaction requests coming in from the JSON RPC client and sends them to the sequencer.
For consistency, we could remove repetition and simply say: 
     "- Pool database: Records transaction requests ... "

2024-06-04 17:30 UTC, EmpieichO commented on docs/zkEVM/architecture/high-level/overview.md
>      - State database: The state database responds to read requests from the JSON RPC client.
Same here: 
  "- State database: Responds to ..."

2024-06-04 17:30 UTC, EmpieichO commented on docs/zkEVM/architecture/high-level/overview.md
>      - Pool database: The pool database records transaction requests coming in from the JSON RPC client and sends them to the sequencer.
The other thing here is that:
   It is not true that the Pool database "sends them[transaction requests] to the sequencer". The sequencer selects transactions from the pool and leaves according to its own prioritization.

2024-06-04 17:30 UTC, EmpieichO commented on docs/zkEVM/architecture/high-level/overview.md
>      - Aggregator: Used for aggregating transaction batches to send to the prover. See the discussion on [aggregators](../../architecture/index.md#aggregator) for more information.
For uniformity, I would suggest starting with a verb as in the lines above:
     "- Aggregator: Aggregates transaction batches to ... "

2024-06-04 17:30 UTC, EmpieichO commented on docs/zkEVM/architecture/high-level/overview.md
>      - Synchronizer: This component ensures a synchronized state between the node's systems and the L1 outside-world via the Etherman component and the state database.
Again for consistency, I would suggest omitting "This component" ... and rather say 
   - Synchronizer: Ensures a synchronized state between ... "

2024-06-04 17:30 UTC, EmpieichO commented on docs/zkEVM/architecture/high-level/overview.md
> +    - Etherman component: The Etherman helps the synchronizer maintain a synchronized state with L1 by communicating with the L1 Ethereum chain via smart contract functions.
Again for consistency: Remove "The Etherman" ... to makle it read like this ... 
    - Etherman component: Helps the synchronizer maintain ... "

2024-06-04 17:30 UTC, EmpieichO commented on docs/zkEVM/architecture/high-level/overview.md
>  - Bridge service component: Provides an API to perform bridge claims, i.e. asset and message transfers between L1/L2 and L2/L2.
Since this is part of a list of components, there's no need to call it a component ... more so, this was not done with all the other components. I suggest that you change it to read as follows: 
    "- Bridge service: Provides an API to perform ... "

2024-06-04 17:30 UTC, EmpieichO commented on docs/zkEVM/architecture/high-level/overview.md
>  - Prover component: System for calculating zero-knowledge proofs on transaction batches.
Same comment as above: Remove the word "component" for consistency.

2024-06-04 17:30 UTC, EmpieichO commented on docs/zkEVM/architecture/high-level/smart-contracts/api/lib/PolygonZkEVMGlobalExitRootBaseStorage.md
> +### `lastRollupExitRoo`
These items; 
`lastRollupExitRoot`, `lastMainnetExitRoot` and `globalExitRootMap` 
appearing in “PolygonZkEVMGlobalExitRootBaseStorage.md” do not look like functions.

In “contracts/PolygonZkEVMGlobalExitRoot.sol” here https://github.com/0xPolygonHermez/zkevm-contracts/blob/1ad7089d04910c319a257ff4f3674ffd6fc6e64e/contracts/PolygonZkEVMGlobalExitRoot.sol#L18 
they are not functions but ... variables.

I was making corrections using the code in the above link until I realised that I am probably looking at the wrong code.

Could you supply the link from which you got the updated info mentioned in line 21?

2024-06-04 17:30 UTC, EmpieichO commented on docs/zkEVM/architecture/high-level/smart-contracts/api/lib/PolygonZkEVMGlobalExitRootBaseStorage.md
> +## Functions
These items; 
`lastRollupExitRoot`, `lastMainnetExitRoot` and `globalExitRootMap` 
appearing in “PolygonZkEVMGlobalExitRootBaseStorage.md” do not look like functions.

In “contracts/PolygonZkEVMGlobalExitRoot.sol” here https://github.com/0xPolygonHermez/zkevm-contracts/blob/1ad7089d04910c319a257ff4f3674ffd6fc6e64e/contracts/PolygonZkEVMGlobalExitRoot.sol#L18 
they are variables ... and not functions.

I was making corrections using the code in the above link until I realise that I am probably looking at the wrong code.

Could you supply the link from which you got the updated info mentioned in line 21: “Note that global exit roots in previous versions recorded `timestamp` instead of `blockhash`.”

2024-06-04 17:30 UTC, EmpieichO commented on docs/zkEVM/architecture/high-level/smart-contracts/bridging.md
> +The unified bridge transfers assets and messages between networks (L1, L2) by calling bridge and claim functions on the [PolygonZkEVMBridgeV2.sol](https://github.com/0xPolygonHermez/zkevm-contracts/b
I would omit the last part of the sentence: "which is an upgradeable proxy" ... as it does seem to be extra info.  
But it's because I am not sure that this contract is a proxy. Although upgradeable ... it is not necesssarily a proxy.

2024-06-04 17:31 UTC, EmpieichO commented
I have gone as far as this doc:
docs/zkEVM/architecture/high-level/smart-contracts/bridging.md

Please look at the suggestions and make corrections.

I am struggling to find the flow in these two docs: 
docs/zkEVM/architecture/high-level/smart-contracts/bridging.md … 
and this one:
docs/zkEVM/architecture/high-level/smart-contracts/exit-roots.md 

I don’t know if you can revise the `narration` a bit? In both docs.

2024-06-05 06:44 UTC, kmurphypolygon commented on docs/zkEVM/architecture/high-level/overview.md
>      - Pool database: The pool database records transaction requests coming in from the JSON RPC client and sends them to the sequencer.
the sequencer fetches tx's from the pool .. but this is the next point ... i'll change the word to "passes" if it helps

2024-06-05 06:48 UTC, kmurphypolygon commented on docs/zkEVM/architecture/high-level/smart-contracts/api/lib/PolygonZkEVMGlobalExitRootBaseStorage.md
> +### `lastRollupExitRoo`
you are right, they are variables.. i'll update this whole thing, there was nothing in the doc basically https://github.com/0xPolygonHermez/zkevm-contracts/blob/1ad7089d04910c319a257ff4f3674ffd6fc6e64e/docs/v2/lib/PolygonZkEVMGlobalExitRootBaseStorage.md

2024-06-05 06:50 UTC, kmurphypolygon commented on docs/zkEVM/architecture/high-level/smart-contracts/api/lib/PolygonZkEVMGlobalExitRootBaseStorage.md
> +### `lastRollupExitRoo`
done

2024-06-05 06:50 UTC, kmurphypolygon commented on docs/zkEVM/architecture/high-level/smart-contracts/bridging.md
> +The unified bridge transfers assets and messages between networks (L1, L2) by calling bridge and claim functions on the [PolygonZkEVMBridgeV2.sol](https://github.com/0xPolygonHermez/zkevm-contracts/b
yeah, confirming on this one with Omnifient now ...

2024-06-05 08:07 UTC, EmpieichO commented on docs/zkEVM/architecture/high-level/overview.md
>      - Pool database: The pool database records transaction requests coming in from the JSON RPC client and sends them to the sequencer.
With regards to this section you could use the same language as used in here https://docs.polygon.technology/cdk/architecture/cdk-zkevm/ ... as well as what Jose used in the "Effective gas price" doc.

2024-06-05 08:33 UTC, EmpieichO commented on docs/zkEVM/architecture/high-level/smart-contracts/bridging.md
> +1. When a batch of transactions is processed, the bridge contract appends the L2 exit tree with a new leaf containing the batch information. This updates the L2 exit tree root.
When a batch of transactions is processed, the bridge contract appends a new leaf containing the batch information to the L2 exit tree, and thus updating the L2 exit tree root.

2024-06-05 08:40 UTC, EmpieichO commented on docs/zkEVM/architecture/high-level/smart-contracts/exit-roots.md
> +The use of two distinct global exit root manager contracts for L1 and L2, as well as separate logic for the sequencing flow and the bridge contract, allows for extensive network interoperability. Mea
The use of two distinct global exit root manager contracts for L1 and L2, as well as a separate logic for the sequencing flow and the bridge contract, allows for extensive network interoperability. Meanwhile, all asset transfers can be validated by any L1 and L2 node due to the accessibility of state data.

2024-06-05 08:42 UTC, EmpieichO commented on docs/zkEVM/architecture/high-level/smart-contracts/exit-roots.md
> +The `PolygonZkEVMGlobalExitRootV2` contract manages updates to the exit roots on sequencing The contract calls `updateExitRoot(...)` on the `GlobalExitRootManager` during the sequencing flow to add a
The `PolygonZkEVMGlobalExitRootV2` contract manages updates to the exit roots when sequencing. The contract calls `updateExitRoot(...)` on the `GlobalExitRootManager` during the sequencing flow to add an exit leaf to the relevant exit tree.

2024-06-05 08:53 UTC, EmpieichO commented on docs/zkEVM/architecture/high-level/smart-contracts/main-contracts.md
> +- Stores every global exit root in the `globalExitRootMap`. The root of this map is the timestamp.
The use of a "root" of a map ... something that is not a Merkle tree ... is not clear here.

2024-06-05 08:54 UTC, EmpieichO commented on docs/zkEVM/architecture/high-level/smart-contracts/main-contracts.md
> +- Stores every global exit root in the `globalExitRootMap`. The root of this map is the timestamp.
Trying to understand the concept of a "root" when referring to a map.

2024-06-05 09:06 UTC, EmpieichO commented on docs/zkEVM/architecture/protocol/unified-LxLy/lxly-bridge.md
>  Once sequenced batches have been verified, the _Global Exit Tree_ gets updated, in an approach similar to the zkEVM Bridge Version-1.
Once sequenced batches have been verified, the _Global Exit Tree_ gets updated following a similar approach used for the zkEVM Bridge Version-1.

2024-06-05 09:07 UTC, EmpieichO commented on docs/zkEVM/architecture/protocol/unified-LxLy/lxly-bridge.md
>  The idea of handling verification of several networks in a single contract, is a pre-cursor to the ultimate and envisaged _interop layer_ for the Polygon ecosystem.
The idea of handling verification of several networks in a single contract is a pre-cursor to the ultimate and envisaged _interop layer_ for the Polygon ecosystem.

2024-06-05 09:08 UTC, EmpieichO approved these changes

2024-06-05 10:19 UTC, kmurphypolygon commented on docs/zkEVM/architecture/high-level/smart-contracts/main-contracts.md
> +- Stores every global exit root in the `globalExitRootMap`. The root of this map is the timestamp.
checking

2024-06-05 10:21 UTC, kmurphypolygon commented on docs/zkEVM/architecture/protocol/unified-LxLy/lxly-bridge.md
>  Once sequenced batches have been verified, the _Global Exit Tree_ gets updated, in an approach similar to the zkEVM Bridge Version-1.
You are the original author :D

2024-06-05 10:21 UTC, kmurphypolygon commented on docs/zkEVM/architecture/protocol/unified-LxLy/lxly-bridge.md
>  The idea of handling verification of several networks in a single contract, is a pre-cursor to the ultimate and envisaged _interop layer_ for the Polygon ecosystem.
You are the author here.

2024-06-05 10:28 UTC, merged