Draft: AggLayer documentation in Innovation & design section
0xPolygon/polygon-docs-old pull request #514
Opened 2024-06-06 07:35 UTC by kmurphypolygon

Working with @Jaime-N to produce some docs the AggLayer

Draft gdoc:
https://docs.google.com/document/d/183mqo9N1HbN48RZqDB6StII32hdZU9zlpUS5mDSgrN0/edit#heading=h.bjgmnzcd4kcc

2024-07-08 23:24 UTC, kmurphypolygon commented
@Jaime-N is doing a review so I removed @hsutaiyu

2024-07-12 21:38 UTC, Jaime-N commented on docs/cdk/agglayer/agglayer-go.md
> +The Agglayer Golang service is a web service designed to receive zero-knowledge proofs from various CDK chains, verify their soundness, and send them to L1 for final verification.
```suggestion
The Agglayer Golang is a web service designed to receive zero-knowledge proofs from CDK chains, ensure they are valid, and send them to the L1 verifier contract for final verification.
```

2024-07-12 21:51 UTC, Jaime-N commented on docs/cdk/agglayer/agglayer-go.md
> +    This service is now deprecating in favor of the more robust and efficient [Rust implementation](agglayer-rs.md).
```suggestion
    This service is being deprecated and replaced with a more robust and efficient [Rust implementation](agglayer-rs.md).
```

2024-07-12 21:57 UTC, Jaime-N commented on docs/cdk/agglayer/agglayer-go.md
> +The diagram below shows the full start up, running, and shutdown sequence for the application and its components.
```suggestion
The AggLayer Golang architecture supports interoperability among connected CDK chains by using ZKPs to ensure safety. It uses PostgreSQL database for storage and interacts with both L1 and L2 chains through configured RPC nodes.

The diagram below shows the full start-up, running, and shutdown sequence for the AggLayer Golang application and its components.
```

2024-07-12 21:58 UTC, Jaime-N commented on docs/cdk/agglayer/agglayer-go.md
> +- For each CDK chain it's necessary to configure it's corresponding RPC node, synced with the target CDK.
```suggestion
- For each CDK chain it's necessary to configure its corresponding RPC node, synced with the target CDK. 
```

2024-07-12 22:06 UTC, Jaime-N commented on docs/cdk/agglayer/agglayer-rs.md
> +AggLayer is a Rust-based web service designed to enhance interoperability among heterogeneous blockchain networks by securely handling zero-knowledge proofs.
```suggestion
The AggLayer is a Rust-based web service designed to ensure safety for cross-chain asset transfers among heterogeneous blockchain networks. This safety is provided using ZKPs, allowing end-users to interoperate with no additional trust assumptions.  
```

2024-07-12 22:23 UTC, Jaime-N commented on docs/cdk/agglayer/agglayer-rs.md
> +- Verifier: Confirms the soundness of proofs before submitting them to L1.
```suggestion
- Unified bridge: A shared bridge contract for all AggLayer-connected chains, allowing for the transfer of native assets.
- Pessimistic proof: A novel ZKP that provides safety for the assets on the unified bridge by ensuring no chain can withdraw more tokens of any type than have been deposited into it. The pessimistic proof is validated the verifier contract on the L1. 
```

2024-07-19 21:31 UTC, Jaime-N commented on docs/cdk/agglayer/agglayer-go.md
> +1. Ensure only one instance of Agglayer is running at a time.
```suggestion
1. Ensure only one instance of the Agglayer is running at a time.
```

2024-07-19 21:34 UTC, Jaime-N commented on docs/cdk/agglayer/agglayer-rs.md
> +The service verifies the soundness of proofs from various CDK chains before forwarding them to L1 for verification.
```suggestion
The service verifies the validity of proofs from various CDK chains before forwarding them to L1 for verification.
```

2024-07-19 21:36 UTC, Jaime-N commented on docs/cdk/agglayer/agglayer-rs.md
> +- Pessimistic proof: A novel ZKP that provides safety for the assets on the unified bridge by ensuring no chain can withdraw more tokens of any type than have been deposited into it. The pessimistic
```suggestion
- Unified bridge: A shared bridge contract for all AggLayer-connected chains, allowing for the transfer of fungible tokens. 
- Pessimistic proof: A novel ZKP that provides safety for the tokens deposited to the unified bridge by ensuring no chain can withdraw more tokens of any type than have been deposited into it. Pessimistic proofs are validated by the verifier contract on the L1. 
```

2024-07-19 21:48 UTC, Jaime-N commented on docs/cdk/agglayer/agglayer-rs.md
> +- Input: Proofs from various CDK chains.
```suggestion
- Input: Proofs of execution generated by CDK chains.
```

2024-07-19 21:59 UTC, Jaime-N commented on docs/cdk/agglayer/bridge-and-call.md
> +More complex operations such as bridge an asset and swap it for another asset, or bridge an asset and deposit it into a vault, require implementing custom logic.
```suggestion
The unified bridge allows users to trustlessly bridge a fungible token or message between AggLayer-connected chains.

More complex operations, in which some action is taken on the destination chain with a bridged token, such as a swap, require implementing custom logic. 
```

2024-07-19 22:01 UTC, Jaime-N commented on docs/cdk/agglayer/overview.md
> +While most rollup environments follow a modular approach, where developers pick-and-choose components such as execution and data availability layers for example, the Agglayer vision is uniquely cente
```suggestion
The AggLayer is an in-development interoperability protocol that allows for trustless, cross-chain token transfers and message-passing, as well as more complex operations. The safety of the AggLayer is provided by zero-knowledge proofs.
```

2024-07-22 07:25 UTC, kmurphypolygon commented on docs/cdk/agglayer/agglayer-go.md
> +1. Ensure only one instance of Agglayer is running at a time.
updated over a previous update

2024-07-22 07:32 UTC, kmurphypolygon commented on docs/cdk/agglayer/agglayer-rs.md
> +- Pessimistic proof: A novel ZKP that provides safety for the assets on the unified bridge by ensuring no chain can withdraw more tokens of any type than have been deposited into it. The pessimistic
querying this one

2024-07-26 15:36 UTC, Jaime-N commented on docs/cdk/agglayer/unified-bridge.md
> +Each chain holds a single data structure which stores a record of all token withdrawals and messages that originated from that chain. This “exit tree” is an append-only Merkle trie, similar in struct
```suggestion
Each chain holds a single data structure which stores a record of all token withdrawals and messages that originated from that chain. This “exit tree” is an append-only Merkle trie, similar in structure to the Ethereum deposit trie. The latest state of each chain and the unified bridge is represented by the root of this Merkle tree, referred to as the “exit root.”
```

2024-07-26 15:38 UTC, Jaime-N commented on docs/cdk/agglayer/unified-bridge.md
> +An Ethereum scalability solution, the unified bridge facilitates seamless L1-L2 interaction and relies on robust and secure zero-knowledge proofs.
```suggestion
## Overview

The unified bridge is a single bridge contract on Ethereum, providing a safe, common access point for the transfer of all native, never-wrapped tokens. Each chain has a local copy of the unified bridge root, enabling cross-chain interoperability that doesn’t require the security risks of third-party bridges

```

2024-07-26 15:41 UTC, Jaime-N requested changes
I submitted two changes to the Unified Bridge material. Once those are approved, it's good to merge!

2024-07-26 15:47 UTC, Jaime-N approved these changes

2024-07-26 15:48 UTC, merged