Updating polyfill url
0xPolygon/polygon-docs-old pull request #573
Opened 2024-06-26 21:05 UTC by djpolygon

Updating polyfill to cloudflare service.

2024-06-26 22:11 UTC, rekibnikufesin approved these changes

2024-06-27 09:51 UTC, mt-polygon-technology requested changes
https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6

2024-06-27 09:51 UTC, mt-polygon-technology commented on mkdocs.yml
> +  - https://cdnjs.cloudflare.com/polyfill/
https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6

2024-06-27 11:15 UTC, EmpieichO approved these changes

2024-06-27 11:25 UTC, hsutaiyu approved these changes

2024-06-27 11:25 UTC, hsutaiyu commented on mkdocs.yml
> +  - https://cdnjs.cloudflare.com/polyfill/
```suggestion
  - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6
```

2024-06-27 12:03 UTC, mt-polygon-technology approved these changes

2024-06-27 12:10 UTC, merged