AggLayer - Add a new connected chain list
0xPolygon/polygon-docs-old pull request #660
Opened 2024-08-20 14:59 UTC by EmpieichO

AggLayer - Add a new connected chain list ... as per issue https://polygon.atlassian.net/browse/DOCS-343

2024-08-20 19:46 UTC, Sharonbc01 requested changes
Can it be added in alphabetical order like all the other chain please

2024-08-21 10:37 UTC, hsutaiyu approved these changes

2024-08-21 10:37 UTC, hsutaiyu commented on docs/cdk/agglayer/overview.md
> +The AggLayer service is a service designed to receive ZK proofs from various CDK chains and verify their validity before sending them to the L1 for final settlement. Currently, the AggLayer service h
```suggestion
The AggLayer service is designed to receive ZK proofs from various CDK and non-CDK chains, and verify their validity before sending them to the L1 Ethereum for final settlement. Currently, the AggLayer service has two implementations: [agglayer-go](agglayer-go.md) and [agglayer-rs](agglayer-rs.md).
```

2024-08-21 10:43 UTC, EmpieichO commented
Okay, ... it's in alphabetical order now @Sharonbc01

2024-08-21 12:59 UTC, Sharonbc01 approved these changes

2024-08-21 14:57 UTC, merged