Update - 'Plasma' mentions removed
0xPolygon/polygon-docs-old pull request #77
Opened 2023-12-13 17:33 UTC by EmpieichO

Update - 'Plasma' mentions removed in 4 docs.

2023-12-13 20:15 UTC, kmurphypolygon commented on docs/pos/concepts/tokens/pol.md
> +### How does the modified Bridge function?
```suggestion
### How does the modified bridge function?
```

2023-12-13 20:18 UTC, kmurphypolygon requested changes
Looks good. I wonder about exit queue, seems to be a general thing rather than a proper noun. Also bridge.

2023-12-13 20:18 UTC, kmurphypolygon commented on docs/pos/concepts/tokens/pol.md
> +The Bridge will undergo modifications, with community approval, to change the native token of Polygon PoS to the new POL token. Specifically, the following changes are being proposed:
```suggestion
The bridge will undergo modifications, with community approval, to change the native token of Polygon PoS to the new POL token. Specifically, the following changes are being proposed:
```

2023-12-13 20:18 UTC, kmurphypolygon commented on docs/pos/overview.md
> +6. **Asset transfer (optional)**: If needed, assets can be transferred back to the Ethereum mainnet via the Exit Queue in the core contracts.
```suggestion
6. **Asset transfer (optional)**: If needed, assets can be transferred back to the Ethereum mainnet via the exit queue in the core contracts.
```

2023-12-13 20:18 UTC, kmurphypolygon commented on docs/pos/overview.md
> +The core contracts on the Ethereum mainnet incorporate two key features for security and functionality: fraud proofs and the Exit Queue. Fraud proofs act as a security layer, enabling the validation
```suggestion
The core contracts on the Ethereum mainnet incorporate two key features for security and functionality: fraud proofs and the exit queue. Fraud proofs act as a security layer, enabling the validation of transactions and state changes to ensure transparency and security across operations. The exit queue manages the safe and efficient transfer of assets back to the Ethereum mainnet, allowing users to seamlessly move assets between the Polygon PoS chain and Ethereum without compromising data integrity or security.
```

2023-12-13 20:18 UTC, kmurphypolygon commented on docs/tools/matic-js/advanced/exit-util.md
> +Every bridge client including **POSClient** exposes `exitUtil` property.
```suggestion
Every bridge client, including `POSClient` exposes the `exitUtil` property.
```

2023-12-14 13:47 UTC, EmpieichO reviewed
changes accepted

2023-12-14 13:58 UTC, kmurphypolygon approved these changes

2023-12-14 13:58 UTC, merged