Update PoS - fixed link + MS styling
0xPolygon/polygon-docs-old pull request #88
Opened 2023-12-18 13:16 UTC by EmpieichO

WIP: Update PoS - fixed link + MS styling

2023-12-18 20:20 UTC, EmpieichO commented
This PR is ready for review and approval.

2023-12-19 07:50 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegate.md
> +# How to Delegate
```suggestion
# How to delegate
```

2023-12-19 07:50 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegate.md
> +## Delegate to a Validator
```suggestion
## Delegate to a validator
```

2023-12-19 07:50 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegate.md
> +## Unbond from a Validator
```suggestion
## Unbond from a validator
```

2023-12-19 07:51 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +### What is the Staking Dashboard URL?
```suggestion
### What is the staking dashboard URL?
```

2023-12-19 07:52 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +Please use the [Staking Rewards Calculator](https://staking.polygon.technology/rewards-calculator) to determine your estimates.
```suggestion
Please use the [Polygon earnings calculator](https://staking.polygon.technology/rewards-calculator) to determine your estimates.
```

2023-12-19 07:53 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +### Do I need ETH to pay for Gas fees?
```suggestion
### Do I need ETH to pay for gas fees?
```

2023-12-19 07:53 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +### Do I need to deposit MATIC tokens to the Polygon Mainnet network for staking?
```suggestion
### Do I need to deposit MATIC tokens to the Polygon mainnet network for staking?
```

2023-12-19 07:53 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +### When I try to do the transaction my Confirm button is disabled, why so?
```suggestion
### When I try to do the transaction my **Confirm** button is disabled.
```

2023-12-19 07:53 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +No. All your funds need to be on the Main Ethereum Network.
```suggestion
No. All your funds need to be on the main Ethereum network.
```

2023-12-19 07:54 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +### What is the Unbonding period?
```suggestion
### What is the unbonding period?
```

2023-12-19 07:54 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +
```suggestion
```

2023-12-19 07:54 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +### What does Redelegate Rewards mean?
```suggestion
### What does redelegate rewards mean?
```

2023-12-19 07:55 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +### Which browser is compatible with Staking Dashboard?
```suggestion
### Which browser is compatible with the Polygon earnings calculator?
```

2023-12-19 07:56 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +Technically, the Polygon Wallet Suite/Staking interface is just a web application. Currently it supports the following wallets - Metamask, WalletConnect, and WalletLink.
```suggestion
Technically, the Polygon Wallet Suite interface is just a web application. Currently it supports the following wallets - Metamask, WalletConnect, and WalletLink.
```

2023-12-19 07:57 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +Technically, the Polygon Wallet Suite/Staking interface is just a web application. Currently it supports the following wallets - Metamask, WalletConnect, and WalletLink.
removed list of wallets as it looks like there's much more now

2023-12-19 07:58 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +### I have delegated my tokens via MetaMask on the Staking dashboard. Do I need to keep my system or device on?
```suggestion
### I have delegated my tokens via MetaMask on the dashboard. Do I need to keep my system or device on?
```

2023-12-19 07:58 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +No. Once your Delegation transactions are confirmed, and you can see your tokens reflected in the **Total Stake** and **New Reward** sections, then you are done. There is no need to keep your system
```suggestion
No. Once your delegation transactions are confirmed, and you can see your tokens reflected in the **Total Stake** and **New Reward** sections, then you are done. There is no need to keep your system or device on.
```

2023-12-19 07:59 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +### I have unbonded, how long will it take to Unbond?
```suggestion
### I have unbonded, how long will it take to unbond?
```

2023-12-19 07:59 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +### I have unbonded, and I now see the Claim Stake button, but it is disabled, why is that?
```suggestion
### I have unbonded, and I now see the **Claim Stake** button, but it is disabled.
```

2023-12-19 07:59 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +### Do I know when will the Claim Stake button be enabled?
```suggestion
### When will the **Claim Stake** button be enabled?
```

2023-12-19 08:00 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +Yes, under the Claim Stake button you would see a note on how many checkpoints are pending before the Claim Stake button would be enabled. Every checkpoint takes approximately 30 minutes. However, so
```suggestion
Under the **Claim Stake** button you should see a note on how many checkpoints are pending before the **Claim Stake** button is enabled. Every checkpoint takes approximately 30 minutes. However, some checkpoints could be delayed upto ~1 hour due to congestion on Ethereum.
```

2023-12-19 08:01 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +
```suggestion
```

2023-12-19 08:01 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +
```suggestion
```

2023-12-19 08:01 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +<!-->
```suggestion
```

2023-12-19 08:01 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +### Have the Foundations nodes been turned off?
```suggestion
### Have the foundations nodes been turned off?
```

2023-12-19 08:01 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +### Will there be any Foundation nodes in the future?
```suggestion
### Will there be any foundation nodes in the future?
```

2023-12-19 08:02 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +### How many transactions do I need to pay for Gas when I do a Move Stake?
```suggestion
### How many transactions do I need to pay for gas when I do a **Move Stake**?
```

2023-12-19 08:03 UTC, kmurphypolygon commented on docs/pos/operate-node/delegate/delegator-faq.md
> +The Move Stake is a single transaction only. All transactions would be on the Ethereum Blockchain so you would need to spend some ETH while doing the Move Stake transaction.
```suggestion
The Move Stake is a single transaction only. All transactions would be on the Ethereum Blockchain so you would need to spend some ETH while doing the Move Stake transaction.
```
```suggestion
The move stake is a single transaction only. All transactions are on the Ethereum blockchain so you will spend some ETH to make the transaction.
```

2023-12-19 08:03 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/run-validator/binaries.md
> +## Port Configuration Details
```suggestion
## Port configuration details
```

2023-12-19 08:03 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/run-validator/binaries.md
> +Here are a few instructions on how to configure ports for Sentry and Validator nodes.
```suggestion
Here are a few instructions on how to configure ports for sentry and validator nodes.
```

2023-12-19 08:04 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/run-validator/binaries.md
> +### For Sentry nodes
```suggestion
### For sentry nodes
```

2023-12-19 08:04 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/run-validator/binaries.md
> +### For Validator nodes
```suggestion
### For validator nodes
```

2023-12-19 08:04 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/staking-faq.md
> +### I am unable to view the Staking tab. How do I access Staking?
```suggestion
### I am unable to view the staking tab. How do I access staking?
```

2023-12-19 08:05 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/staking-faq.md
> +### How do I know which Validator to select for better rewards?
```suggestion
### How do I know which validator to select for better rewards?
```

2023-12-19 08:06 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/staking-faq.md
> +### How to unbond?
Just a note here Anthony, is this duplicate information ... ? Also, I remember from yesterday they are talking about consolidating these FAQs ... so I'm wondering if this is unnecessary work right now..

2023-12-19 08:06 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/staking-faq.md
> +To Unbond from a Validator, navigate to MyAccount, where you find "Your Delegations".
```suggestion
To unbond from a validator, navigate to MyAccount, where you find "Your Delegations".
```

2023-12-19 08:07 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/staking-faq.md
> +There you will see an Unbond button for each of the validators. Click on the Unbond button for whichever validator that you want to unbond from.
```suggestion
There you will see an **Unbond** button for each of the validators. Click on the **Unbond** button for whichever validator that you want to unbond from.
```

2023-12-19 08:07 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/staking-faq.md
> +Go to “My Account” to check "Your Delegations".
```suggestion
Go to **My Account** to check **Your Delegations**.
```

2023-12-19 08:07 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/staking-faq.md
> +Clicking on "Restake Reward" will ask you for confirmation from your wallet account. Once you confirm the transaction, only then the restake transaction would be complete.
```suggestion
Clicking on **Restake Reward** will ask you for confirmation from your wallet account. Once you confirm the transaction, only then the restake transaction would be complete.
```

2023-12-19 08:07 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/staking-faq.md
> +### I want to Restake Rewards but I am unable to.
```suggestion
### I want to restake rewards but I am unable to.
```

2023-12-19 08:08 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/staking-faq.md
> +You can claim your rewards by clicking on the “My Account”, all the delegators for a validator are displayed. Click on the “Withdraw Reward” button and the rewards will be transferred to your delegat
```suggestion
You can claim your rewards by clicking on the **My Account**, all the delegators for a validator are displayed. Click on the **Withdraw Reward** button and the rewards will be transferred to your delegated account in wallet.
```

2023-12-19 08:08 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/staking-faq.md
> +### I want to Withdraw Rewards but I am unable to.
```suggestion
### I want to withdraw rewards but I am unable to.
```

2023-12-19 08:08 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/staking-faq.md
> +Once the **unbonding period is complete**, the Claim Stake button will be enabled and you can then claim your staked tokens. The tokens will be transferred to your account.
```suggestion
Once the unbonding period is complete, the **Claim Stake** button will be enabled and you can then claim your staked tokens. The tokens will be transferred to your account.
```

2023-12-19 08:09 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/staking-faq.md
> +Yes, hardware wallets are supported. You can use the "Connect Hardware Wallet" option on MetaMask and connect your Hardware wallet and then continue the delegation process.
```suggestion
Yes, hardware wallets are supported. You can use the **Connect Hardware Wallet** option on MetaMask and connect your Hardware wallet and then continue the delegation process.
```

2023-12-19 08:09 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/staking-faq.md
> +### Do I need to deposit Matic to the Polygon Mainnet network for staking?
```suggestion
### Do I need to deposit Matic to the Polygon mainnet network for staking?
```

2023-12-19 08:09 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/staking-faq.md
> +No. All your funds need to be on the Main Ethereum Network.
```suggestion
No. All your funds need to be on the Ethereum mainnet.
```

2023-12-19 08:10 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/staking-faq.md
> + Yes, you just have to reach "Your Delegations", click on "Move Stake", and then choose your new validator.
```suggestion
 Yes, you just have to access **Your Delegations**, click on **Move Stake**, and then choose your new validator.
```

2023-12-19 08:10 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/staking-faq.md
> + Yes, you just have to reach "Your Delegations", click on "Move Stake", and then choose your new validator.
reach is an odd word here!

2023-12-19 08:10 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/staking-faq.md
> +### Which browsers are compatible with the Staking Dashboard?
```suggestion
### Which browsers are compatible with the staking dashboard?
```

2023-12-19 08:10 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/staking-faq.md
> +- If you’re using Brave, please turn off the option for “Use Crypto Wallets” in the settings panel.
```suggestion
- If you’re using Brave, please turn off the option for **Use Crypto Wallets** in the settings panel.
```

2023-12-19 08:11 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/technical-faqs.md
>  ### 15. What if someone become a Top 10 staker, how he will receive his MATIC reward at the end?
```suggestion
### 15. What if someone become a top 10 staker, how he will receive his MATIC reward at the end?
```

2023-12-19 08:12 UTC, kmurphypolygon commented on docs/pos/operate-node/validator/technical-faqs.md
>  ### 16. What should be my heimdall version?
```suggestion
### 16. What should the Heimdall version be?
```

2023-12-19 08:20 UTC, 0xgraciegrace approved these changes

2023-12-19 08:24 UTC, 0xgraciegrace approved these changes

2023-12-19 08:24 UTC, kmurphypolygon requested changes
Some comments/suggestions.

Some of the images are a little large. You can make them smaller by adding a small css at the end of the entry. For example: https://docs-staging.polygon.technology/tools/wallets/wallet-link/#configure-polygon-on-walletlink

```    
<center>
    ![Create an account](../../img/tools/wallet/walletlink/config-polygon-walletlink-1.jpg){ width="50%" }
    </center>
```

2023-12-19 09:03 UTC, EmpieichO commented on docs/pos/operate-node/delegate/delegator-faq.md
> +
@kmurphypolygon 
What is the reason for the deletion of this content? 
Well, I can see most of it could use some editing, which i didn't do. You don't think Alex needs the info ?

2023-12-19 09:06 UTC, EmpieichO commented on docs/pos/operate-node/delegate/delegator-faq.md
> +<!-->
@kmurphypolygon I have the same question here as above.

2023-12-19 09:17 UTC, EmpieichO commented on docs/pos/operate-node/validator/staking-faq.md
> +### How to unbond?
@kmurphypolygon 
I included these files as per Alex Ovarbor's request in the late afternoon yesterday ... after our meeting.
I would rather be the Solution Engineers who request info to be removed rather than having redo because they still can't find what they want. See what I mean?

2023-12-19 09:28 UTC, EmpieichO commented on docs/pos/operate-node/validator/staking-faq.md
> +### How to unbond?
@kmurphypolygon 
This is a thorough review. Thank you.
I focused on migrating the required docs, ... adjusting admonitions, links to images/videos, and the proper rendering e.g., serial list numbering ... 
So I didn't do any editing.

2023-12-19 09:37 UTC, kmurphypolygon approved these changes

2023-12-19 09:38 UTC, merged