added supra to oracle documentation
0xPolygon/polygon-docs-old pull request #96
Opened 2023-12-19 15:09 UTC by ksdumont

Supra launched oracle services to Polygon mainnet. I updated your oracle documentation to add Supra to the list.

2023-12-19 16:49 UTC, kmurphypolygon commented on docs/tools/oracles/supra.md
> +**Supra** is a novel, high-throughput Oracle & IntraLayer: A vertically integrated toolkit of cross-chain solutions (data oracles, asset bridges, automation network, and more) that interlink all bloc
```suggestion
**Supra** is a novel, high-throughput oracle & intralayer: A vertically integrated toolkit of cross-chain solutions (data oracles, asset bridges, automation network, and more) that interlink all blockchains, public (L1s and L2s) or private (enterprises).
```

2023-12-19 16:51 UTC, kmurphypolygon commented on docs/tools/oracles/supra.md
> +[Supra](https://supraoracles.com/) provides decentralized oracle price feeds that can be used for on-chain and off-chain use-cases such as spot and perpetual DEXes, lending protocols, and payments pr
```suggestion
[Supra](https://supraoracles.com/) provides decentralized oracle price feeds that can be used for on-chain and off-chain use-cases such as spot and perpetual DEXes, lending protocols, and payments protocols. Supra’s oracle chain and consensus algorithm makes it the fastest-to-finality oracle provider, with layer-1 security guarantees. The pull oracle has a sub-second response time. Aside from speed and security, Supra’s rotating node architecture gathers data from 40+ data sources and applies a robust calculation methodology to get the most accurate value. The node provenance on the data dashboard also provides a fully transparent historical audit trail. Supra’s Distributed Oracle Agreement (DORA) paper was accepted into ICDCS 2023, the oldest distributed systems conference.
```

2023-12-19 16:51 UTC, kmurphypolygon commented on docs/tools/oracles/supra.md
> +Check out our developer docs [here](https://supraoracles.com/docs/overview/).
```suggestion
Check out our [developer docs](https://supraoracles.com/docs/overview/).
```

2023-12-19 16:51 UTC, kmurphypolygon requested changes
A few tiny changes please.

2023-12-19 17:57 UTC, ksdumont commented
I committed all of your changes, kindly let me know when it is merged.

2023-12-20 07:35 UTC, kmurphypolygon approved these changes

2023-12-20 07:35 UTC, merged

2023-12-20 07:36 UTC, kmurphypolygon commented
Merged and thank you @ksdumont